# Generated by Django 6.0.6 on 2026-06-16 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True, default='')),
                ('value_type', models.CharField(choices=[('string', 'String'), ('text', 'Text'), ('boolean', 'Boolean'), ('integer', 'Integer'), ('email', 'Email'), ('url', 'URL'), ('color', 'Color')], default='string', max_length=20)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
